#!/usr/bin/env python3
"""Parse outputs from tools/scan-proxies and join them into a single JSON file"""
import json
import sys

if len(sys.argv) < 2:
    print(f"Usage: {sys.argv[0]} <file list>", file=sys.stderr)
    sys.exit(1)

filelist = sys.argv[1]
files = open(filelist).read().splitlines()
data = {}
for file in files:
    try:
        j = json.load(open(file))
    except json.decoder.JSONDecodeError:
        print(f"Error parsing {file}", file=sys.stderr)
        continue
    j["address"] = j["address"].lower()
    data[j["address"]] = j

json.dump(data, sys.stdout, indent=2)
